language: java
jdk:
  - oraclejdk8
before_install:
  - nvm install 8.9.4
  - cd ./generator-liberty
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
  - npm install
before_script:
  - cd /tmp
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - wget https://github.com/github/hub/releases/download/v2.2.9/hub-linux-386-2.2.9.tgz
  - unzip -qq gradle-3.5-bin.zip
  - tar -xvzf hub-linux-386-2.2.9.tgz
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PWD/hub-linux-386-2.2.9/bin/:$PATH
  - gradle -v
  - git clone -b master https://github.com/ibm-developer/standard-npm-devops.git
  - cd $TRAVIS_BUILD_DIR/generator-liberty
script:
  - npm run lint
  - npm test
  - npm run testint
  - npm run coveralls
  - /tmp/standard-npm-devops/do_devops.sh
branches:
  only:
  - master
  - develop
env:
  - DEV_BRANCH=develop PROD_BRANCH=master DEVOPS_SCRIPT_DIR="/tmp/standard-npm-devops"